spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/contact-app
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  hikari:
    maximum-pool-size: 50
    minimum-idle: 10
    idle-timeout: 30000
    connection-timeout: 30000
    max-lifetime: 1800000
    pool-name: SpringBootHikariCP

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true

  profiles:
    active: dev

  logging:
    level:
      com.zaxxer.hikari: DEBUG
      org:
        hibernate:
          SQL: DEBUG
          type:
            descriptor:
              sql:
                BasicBinder: TRACE
      springframework:
        web: INFO
        jpa: DEBUG